from string import Template

__SELECT_ALL_ANAG_ECONOMICS = "SELECT * FROM ECO_ANAG;"
__SELECT_ALL_VAL_ECONOMICS = "SELECT * FROM ECO_VAL;"
__SELECT_ALL_ANAG_DRIVERS = "SELECT * FROM DRV_ANAG;"
__SELECT_ALL_VAL_DRIVERS = "SELECT * FROM DRV_VAL;"
__SELECT_ALL_MAP_ECONOMICS_DRIVERS = "SELECT * FROM ECO_DRV_MAP;"
__SELECT_ALL_BUDGET_ECONOMICS = "SELECT * FROM ECO_BUDGET;"
__SELECT_ALL_DRIVER_BEST_MODEL = "SELECT * FROM DRV_BEST_MODEL;"
__SELECT_ALL_DRIVER_SELECTED = "SELECT * FROM DRV_SEL;"
__SELECT_ALL_ECO_BEST_MODEL = "SELECT * FROM ECO_BEST_MODEL;"
__SELECT_ALL_ECO_LASSO = "SELECT * FROM ECO_LASSO;"
__SELECT_ALL_ECO_XGBOOST = "SELECT * FROM ECO_XGBOOST;"
__SELECT_ALL_ECO_LASSO_LARS = "SELECT * FROM ECO_LASSO_LARS;"
__SELECT_ALL_DRV_FIT = "SELECT * FROM DRV_FIT;"
__SELECT_ALL_DRV_FORECAST = "SELECT * FROM DRV_FORECAST;"
__SELECT_ALL_ECO_FIT = "SELECT * FROM ECO_FIT;"
__SELECT_ALL_ECO_FORECAST = "SELECT * FROM ECO_FORECAST;"
__SELECT_ALL_ECO_FORECAST_REC = "SELECT * FROM ECO_FORECAST_REC"
__SELECT_ALL_ECO_GROUP_VAL = "SELECT * FROM ECO_GROUP_VAL"
__SELECT_ALL_ECO_GROUP_FIT = "SELECT * FROM ECO_GROUP_FIT"
__SELECT_ALL_CAUSE_EFFECT = "SELECT * FROM CAUSE_EFFECT;"

__SELECT_MAPPED_DRIVERS_WITH_ECONOMICS = """
SELECT
    m.*,
    a.DRV_DSC AS driver_description,
    e_anag.ECO_DSC AS economic_description,
FROM ECO_DRV_MAP m
LEFT JOIN DRV_ANAG a ON m.DRV_COD = a.DRV_COD
LEFT JOIN ECO_ANAG e_anag ON m.ECO_COD = e_anag.ECO_COD
"""

__SELECT_SELECTED_DRIVERS = """
SELECT
    drv.*
FROM DRV_VAL drv INNER JOIN ECO_DRV_MAP map ON drv.DRV_COD = map.DRV_COD WHERE map.${model_selection}_SELECTED = 1 AND map.DRV_COD IN( SELECT DRV_COD
    FROM DRV_BEST_MODEL
    WHERE $score_column <= $score_threshold
);
"""

__SELECT_BEST_MODEL_DRIVER = """
SELECT model
FROM DRV_BEST_MODEL
WHERE DRV_COD = '$id' 
"""

__SELECT_BEST_MODEL_ECO = """
SELECT model
FROM ECO_BEST_MODEL
WHERE ECO_COD = '$id'
"""

__SELECT_ECO_DRIVER_WITH_MODEL_SCORE = """
SELECT DISTINCT DRV_COD
FROM ECO_DRV_MAP
WHERE ECO_COD = '$eco_id'
AND DRV_COD IN (
    SELECT DRV_COD
    FROM DRV_BEST_MODEL
    WHERE $score_column <= $score_threshold
)
"""

__SELECT_DRIVER_FORECAST = """
    SELECT *
    FROM DRV_FORECAST
    WHERE list_contains($driver_codes, DRV_COD)
"""

__CREATE_LASSO_SELECTION_COLUMN = """
    ALTER TABLE ECO_DRV_MAP
    ADD COLUMN LASSO_SELECTED BOOLEAN DEFAULT false
"""
__SELECTED_DRIVER_UPDATE_LASSO = """
    UPDATE ECO_DRV_MAP AS map
    SET LASSO_SELECTED = true
    FROM ECO_DRV_COEFFS AS c
    WHERE map.ECO_COD = c.ECO_COD AND map.DRV_COD = c.DRV_COD AND c.COEFF_LASSO != 0
 """
__CREATE_LASSO_LARS_SELECTION_COLUMN = """
    ALTER TABLE ECO_DRV_MAP
    ADD COLUMN LASSO_LARS_SELECTED BOOLEAN DEFAULT false
"""
__SELECTED_DRIVER_UPDATE_LASSO_LARS = """
    UPDATE ECO_DRV_MAP AS map
    SET LASSO_LARS_SELECTED = true
    FROM ECO_DRV_COEFFS AS c
    WHERE map.ECO_COD = c.ECO_COD AND map.DRV_COD = c.DRV_COD AND c.COEFF_LASSO_LARS != 0
"""
__CREATE_XGBOOST_SELECTION_COLUMN = """
    ALTER TABLE ECO_DRV_MAP
    ADD COLUMN XGBOOST_SELECTED BOOLEAN DEFAULT false
"""
__SELECTED_DRIVER_UPDATE_XGBOOST = """
    UPDATE ECO_DRV_MAP AS map
    SET XGBOOST_SELECTED = true
    FROM ECO_DRV_IMPORTANCE AS imp
    WHERE map.ECO_COD = imp.ECO_COD AND map.DRV_COD = imp.DRV_COD
"""

QUERY_MAP = {
    "all_anag_economics": __SELECT_ALL_ANAG_ECONOMICS,
    "all_val_economics": __SELECT_ALL_VAL_ECONOMICS,
    "all_anag_drivers": __SELECT_ALL_ANAG_DRIVERS,
    "all_val_drivers": __SELECT_ALL_VAL_DRIVERS,
    "all_map_economics_drivers": __SELECT_ALL_MAP_ECONOMICS_DRIVERS,
    "all_budget_economics": __SELECT_ALL_BUDGET_ECONOMICS,
    "mapped_drivers_with_economics": __SELECT_MAPPED_DRIVERS_WITH_ECONOMICS,
    "selected_drivers": Template(__SELECT_SELECTED_DRIVERS),
    "best_model_driver": Template(__SELECT_BEST_MODEL_DRIVER),
    "best_model_eco": Template(__SELECT_BEST_MODEL_ECO),
    "eco_driver_with_model_score": Template(__SELECT_ECO_DRIVER_WITH_MODEL_SCORE),
    "driver_forecast": Template(__SELECT_DRIVER_FORECAST),
    "create_lasso_selection_column": __CREATE_LASSO_SELECTION_COLUMN,
    "create_lasso_lars_selection_column": __CREATE_LASSO_LARS_SELECTION_COLUMN,
    "create_xgboost_selection_column": __CREATE_XGBOOST_SELECTION_COLUMN,
    "selected_driver_lasso": __SELECTED_DRIVER_UPDATE_LASSO,
    "selected_driver_lasso_lars": __SELECTED_DRIVER_UPDATE_LASSO_LARS,
    "selected_driver_xgboost": __SELECTED_DRIVER_UPDATE_XGBOOST,
    "all_driver_best_model": __SELECT_ALL_DRIVER_BEST_MODEL,
    "all_driver_selected": __SELECT_ALL_DRIVER_SELECTED,
    "all_eco_best_model": __SELECT_ALL_ECO_BEST_MODEL,
    "all_eco_lasso": __SELECT_ALL_ECO_LASSO,
    "all_eco_xgboost": __SELECT_ALL_ECO_XGBOOST,
    "all_eco_lasso_lars": __SELECT_ALL_ECO_LASSO_LARS,
    "all_driver_fit": __SELECT_ALL_DRV_FIT,
    "all_driver_forecast": __SELECT_ALL_DRV_FORECAST,
    "all_eco_fit": __SELECT_ALL_ECO_FIT,
    "all_eco_forecast": __SELECT_ALL_ECO_FORECAST,
    "all_forecast_rec": __SELECT_ALL_ECO_FORECAST_REC,
    "all_val_group": __SELECT_ALL_ECO_GROUP_VAL,
    "all_group_fit": __SELECT_ALL_ECO_GROUP_FIT,
    "all_cause_effect": __SELECT_ALL_CAUSE_EFFECT,
}
